ktor:
  application:
    modules:
      - ktor.starter.ApplicationKt.module
  deployment:
    port: 8000
postgres:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: postgres
  password: example